
project '/Users/iOSDeveloper/Desktop/练习测试/Frame/SwiftFrame/SwiftFrame.xcodeproj'
platform :ios, '8.0'

use_frameworks!

target 'SwiftFrame' do

pod 'AFNetworking', '~> 3.1.0'

pod 'SDWebImage', '~> 3.8.2'

pod 'MJRefresh', '~> 3.1.12'

pod 'FMDB', '~> 2.6.2'

pod 'TPKeyboardAvoiding', '~> 1.3'

pod 'MBProgressHUD', '~> 1.0.0'

pod 'JSONKit', '~> 1.5pre'

pod 'Mantle', '~> 2.0.7'

end
